src/Entity/User.php
<?php

namespace App\Entity;

use App\Enumerations\RoleEnumeration;
use App\Repository\UserRepository;
use App\Traits\KeyTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use KeyTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $biography = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $headerimage = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'Owner', targetEntity: Comic::class, orphanRemoval: true)]
    private Collection $comics;

    #[ORM\Column]
    private ?bool $active = false;

    #[ORM\Column]
    private ?bool $deleted = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $requestRole = null;

    #[ORM\OneToMany(mappedBy: 'uploadedby', targetEntity: Page::class, orphanRemoval: true)]
    private Collection $pages;

    #[ORM\Column(type: Types::DATETIMETZ_MUTABLE)]
    private ?\DateTimeInterface $createdon = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?CryptKey $publickey = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?CryptKey $privatekey = null;

    public function __construct()
    {
        $this->comics = new ArrayCollection();
        $this->pages = new ArrayCollection();
        $this->createdon = new \DateTime();
        $this->regenerateKeyPair();
    }

    public function regenerateKeyPair(): static
    {
        $keys = $this->_generateKeyPair();
        $this->publickey = new CryptKey();
        $this->publickey->setData($keys['public']);
        $this->privatekey = new CryptKey();
        $this->privatekey->setData($keys['private']);
        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Comic>
     */
    public function getComics(): Collection
    {
        return $this->comics;
    }

    public function addComic(Comic $comic): static
    {
        if (!$this->comics->contains($comic)) {
            $this->comics->add($comic);
            $comic->addAdmin($this);
        }

        return $this;
    }

    public function removeComic(Comic $comic): static
    {
        if ($this->comics->removeElement($comic)) {
            $comic->removeAdmin($this);
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * Alias for getBiography
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->getBiography();
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(string $biography): static
    {
        $this->biography = $biography;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getIconImageURL(): ?string
    {
        if (!empty($this->image)) {
            return "/usericon/@{$this->username}";
        }
        return null;
    }

    public function getHeaderimage(): ?string
    {
        return $this->headerimage;
    }

    public function setHeaderimage(?string $headerimage): static
    {
        $this->headerimage = $headerimage;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Comic>
     */
    public function getOwnedComics(): Collection
    {
        return $this->comics;
    }

    public function addOwnedComic(Comic $ownedComic): static
    {
        if (!$this->comics->contains($ownedComic)) {
            $this->comics->add($ownedComic);
            $ownedComic->setOwner($this);
        }

        return $this;
    }

    public function removeOwnedComic(Comic $ownedComic): static
    {
        if ($this->comics->removeElement($ownedComic)) {
            // set the owning side to null (unless already changed)
            if ($ownedComic->getOwner() === $this) {
                $ownedComic->setOwner(null);
            }
        }

        return $this;
    }

    public function getIcon(): string
    {
        if (in_array('ROLE_OWNER', $this->roles)) {
            return 'fa-crown';
        } elseif (in_array('ROLE_ADMIN', $this->roles)) {
            return 'fa-screwdriver-wrench';
        } elseif (in_array('ROLE_CREATOR', $this->roles)) {
            return 'fa-palette';
        }
        return 'fa-user';
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): static
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getRequestRole(): ?string
    {
        return $this->requestRole;
    }

    public function setRequestRole(?string $requestRole): static
    {
        $this->requestRole = $requestRole;

        return $this;
    }

    /**
     * @return Collection<int, Page>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
            $page->setUploadedby($this);
        }

        return $this;
    }

    public function removePage(Page $page): static
    {
        if ($this->pages->removeElement($page)) {
            // set the owning side to null (unless already changed)
            if ($page->getUploadedby() === $this) {
                $page->setUploadedby(null);
            }
        }

        return $this;
    }

    public function getCreatedon(): ?\DateTimeInterface
    {
        return $this->createdon;
    }

    public function setCreatedon(\DateTimeInterface $createdon): static
    {
        $this->createdon = $createdon;

        return $this;
    }

    public function getPublickey(): ?CryptKey
    {
        return $this->publickey;
    }

    public function setPublickey(?CryptKey $publickey): static
    {
        $this->publickey = $publickey;

        return $this;
    }

    public function getPrivatekey(): ?CryptKey
    {
        return $this->privatekey;
    }

    public function setPrivatekey(?CryptKey $privatekey): static
    {
        $this->privatekey = $privatekey;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Comic;
use App\Entity\User;
use App\Enumerations\MediaPathEnumeration;
use App\Exceptions\SettingNotFoundException;
use App\Form\CreateComicType;
use App\Form\EditComicType;
use App\Form\UserProfileType;
use App\Helpers\SettingsHelper;
use App\Service\Settings;
use App\Traits\MediaPathTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    use MediaPathTrait;

    #[Route('/profile', name: 'app_profile')]
    public function profile(EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('profile/profile.html.twig', []);

    }


    #[Route('/profile/edit', name: 'app_editprofile')]
    public function editProfile(EntityManagerInterface $entityManager, Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        /**
         * @var User $user
         */
        $user = $this->getUser();
        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);
        try {
            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager->persist($user);
                $entityManager->flush();
                $this->addFlash('info', 'Profile has been updated.');
                return new RedirectResponse($this->generateUrl('app_profile'));
            }
        } catch (\Exception $e){
            $err = new FormError($e->getMessage());
            $form->addError($err);
        }

        return $this->render('profile/edit_profile.html.twig', [
            'profileForm' => $form->createView()
        ]);

    }

    #[Route('/profile/keygen', name: 'app_profilekeygen')]
    public function regeneratePublicAndPrivateKeys(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        /**
         * @var User $user
         */
        $user = $this->getUser();
        $oldPublic = $user->getPublickey();
        $oldPrivate = $user->getPrivatekey();
        if (!empty($oldPublic)) {
            $entityManager->remove($oldPublic);
        }
        if (!empty($oldPrivate)) {
            $entityManager->remove($oldPrivate);
        }
        $user->regenerateKeyPair();
        $entityManager->persist($user);
        $entityManager->flush();
        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }


    #[Route('/profile/requestrole/creator', name: 'app_requestrolecreator')]
    public function requestRoleCreator(EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        /**
         * @var User $user
         */

        $user = $this->getUser();
        if (in_array("ROLE_OWNER", $user->getRoles()) || in_array("ROLE_ADMIN", $user->getRoles())) {
            return new Response('User already has administrative role', 200);
        } elseif (in_array("ROLE_CREATOR", $user->getRoles())) {
            return new Response('User has creator role', 200);
        }

        $user->setRequestRole('creator');
        $entityManager->persist($user);
        $entityManager->flush();

        $this->addFlash('info', 'Creator role request added.');
        return new RedirectResponse($this->generateUrl("app_profile"));

    }



    #[Route('/profile/upload', name: 'app_profileupload')]
    public function uploadImage(EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        /**
         * @var User $user
         */
        $user = $this->getUser();

        $settings = SettingsHelper::init($entityManager);

        $currentMax = ini_get('upload_max_filesize');
        $maxUpload = $settings->get('upload_max_filesize', $currentMax);
        ini_set('upload_max_filesize', $maxUpload);

        $mediapath = $this->getUserPath($settings, $user->getUsername());
        $mediapath = "{$mediapath}/_media";
        if (!is_dir($mediapath)) {
            mkdir($mediapath, 0775, true);
        }
        $files = array_pop($_FILES);
        if (empty($files)) {
            throw new FileNotFoundException("No file was uploaded.");
        }

        move_uploaded_file($files['tmp_name'], "{$mediapath}/{$files['name']}");

        if (!is_file("{$mediapath}/{$files['name']}")) {
            throw new FileNotFoundException("File did not upload.");
        }


        return new JsonResponse([
            'status' => 'uploaded',
            'user' => $user->getUsername(),
            'file' => $files['name']
        ]);


    }


}

templates/profile/createcomic.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create a Comic{% endblock %}

{% block body %}
    {% for flash_error in app.flashes('error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}



    <div class="container">
        <div class="card col-8 offset-2 p-3 mt-5 panel">
            <h1>Create Comic</h1>

            {{ form_errors(createcomicForm) }}

            {{ form_start(createcomicForm) }}
            <div class="row mb-3">
                {{ form_label(createcomicForm.name) }}
                <div class="col">
                        {{ form_widget(createcomicForm.name) }}
                </div>
            </div>

            <div class="mb-3">
                <div class="row">
                    {{ form_label(createcomicForm.slug) }}
                    <div class="col">
                        <div class="input-group">
                            <span class="input-group-text text-default" id="comic-slug-alert">
                                <i class="fas fa-at" id="comic-slug-alert-icon"></i>
                            </span>
                            {{ form_widget(createcomicForm.slug) }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col offset-3 text-small text-white" id="comic-slug-errors"></div>
                </div>
            </div>


            <div class="row mb-3">
                {{ form_label(createcomicForm.description) }}
                <div class="col">
                    {{ form_widget(createcomicForm.description) }}

                </div>
            </div>
            {% if settings.get.require_comic_approval is defined and settings.get.require_comic_approval == true %}
                <div class="row mb-3">
                    <small><strong>Notice:</strong> This server requires administrator approval before new comics can be created.</small>
                </div>
            {% endif %}

            <div class="row mb-3">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-light btn-block"><i class="fas fa-book"></i> Create</button>
                </div>
            </div>
            {{ form_end(createcomicForm) }}
        </div>

    </div>
{% endblock %}


{% block sidebar %}
    {% include "user-sidebar.html.twig" %}
{% endblock %}

templates/profile/edit_profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit my Profile{% endblock %}

{% block body %}

<div class="container">
    <div class="card col p-3 mt-5 panel" id="c4-comic-admin">
        <div class="row mb-3 mb-3">
            <div class="col">
                <h1>Edit Profile: {% if app.user.name is not empty %}{{ app.user.name }}{% else %}{{ app.user.username }}{% endif %}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">

                {{ form_errors(profileForm) }}
                {{ form_start(profileForm) }}


                <div class="row mb-3">
                    {{ form_label(profileForm.image) }}
                    <div class="col">
                        {{ form_widget(profileForm.image) }}
                    </div>

                </div>
{#                <div class="row mb-3">#}
{#                    {{ form_label(profileForm.headerimage) }}#}
{#                    <div class="col">#}
{#                        {{ form_widget(profileForm.headerimage) }}#}
{#                    </div>#}

{#                </div>#}
                <div class="row mb-3">
                    {{ form_label(profileForm.name) }}
                    <div class="col">
                        {{ form_widget(profileForm.name) }}
                    </div>
                </div>
                <div class="row mb-3">
                    {{ form_label(profileForm.biography) }}
                    <div class="col">
                        {{ form_widget(profileForm.biography) }}
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-3 text-end">Keys Generated:</div>
                    <div class="col">{% if app.user.publickey.createdon is defined %}{{ app.user.publickey.createdon|date('Y-m-d') }}{% else %}Never generated{% endif %}</div>
                    <div class="col-4 text-end"><a class="btn btn-light" href="/profile/keygen"><i class="fas fa-key"></i> Regenerate Keys</a></div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 text-end">Public Key:</div>
                    <div class="col ">{% if app.user.publickey.data is defined %}<pre><code>{{ app.user.publickey.data }}</code></pre>{% else %}No Public Key{% endif %}</div>
                </div>

                <div class="row mb-3">
                    <div class="col offset-3">
                        {{ form_widget(profileForm.submit) }}
                    </div>
                </div>



                {{ form_end(profileForm) }}
            </div>

            <div class="col-4">
                <div class="row mb-3">
                    <div class="col">
                        <div class=" dropzone-target text-center" id="profile_icon_dropzone">
                            <div  id="image_upload_spinner_icon" class="col text-center d-none">
                                <i class="fas fa-spinner fa-spin fa-4x"></i>
                            </div>
                            <img src="{% if app.user.image is not empty %}/usericon/@{{ app.user.username }}{% endif %}" class="{% if app.user.image is not empty is empty %}d-none{% endif%} img-fluid" id="usericon_upload_image"  alt="{{ app.user.username }} Icon"/><br/>
                            <span>User Icon</span>
                        </div>

                    </div>
{#                    <div class="col">#}
{#                        <div class=" dropzone-target text-center" id="profile_header_dropzone">#}
{#                            <div  id="image_upload_spinner_banner" class="col text-center d-none">#}
{#                                <i class="fas fa-spinner fa-spin fa-4x"></i>#}
{#                            </div>#}
{#                            <img src="{% if app.user.headerimage is not empty %}/userbanner/@{{ app.user.username }}{% endif %}" class="{% if app.user.image is not empty is empty %}d-none{% endif%} img-fluid" id="userheader_upload_image"  alt="{{ app.user.username }} Header Image"/><br/>#}
{#                            <span>Header Banner</span>#}
{#                        </div>#}

{#                    </div>#}
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <form method="POST" action="/profile/upload" enctype="multipart/form-data" class="dropzone profileicon-upload-dz" id="profileicon_upload_dropzone_form"></form>
                    </div>
{#                    <div class="col">#}
{#                        <form method="POST" action="/profile/upload" enctype="multipart/form-data" class="dropzone profilebanner-upload-dz" id="profilebanner_upload_dropzone_form"></form>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block sidebar %}
    {% include "common/user-sidebar.html.twig" %}
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/sowersm/workspace/docker-apps/clickthulu/app/src/Controller/ProfileController.php'|file_link(0) }}">src/Controller/ProfileController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/sowersm/workspace/docker-apps/clickthulu/app/templates/profile/index.html.twig'|file_link(0) }}">templates/profile/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/profile/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user.username }}'s Profile{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="row border-bottom mb-3">
                    <h3><i class="fas fa-user"></i> Profile</h3>
                </div>
                <div class="row border-bottom mb-3 pb-2">
                    <div class="col-3 text-center">
                        {% if app.user.image is not empty %}
                            <img src='/usericon/@{{ app.user.username }}' alt="{{ app.user.username }}" class="img-fluid img-icon"/><br/>
                        {% else %}
                            <img src="https://gravatar.com/avatar/{{ app.user.username|md5 }}?s=256&d=robohash" alt="{{ app.user.username }}" class="img-fluid img-icon"/><br/>
                        {% endif %}
                        {% if app.user.name %}
                            <strong>{{ app.user.name }}</strong><br/>
                        {% else %}
                            <strong>{{ app.user.username }}</strong><br/>
                        {% endif %}
                        {% set locbits = settings.get.server_url|split('://') %}
                        <small>@{{ app.user.username }}@{{ locbits[1] }}</small>
                    </div>
                    <div class="col">
                        <div class="row mb-3">
                            <div class="col">
                                {{ app.user.biography|raw }}
                            </div>
                        </div>

                    </div>
                    <div class="col-3">
                        <div class="row mb-3">
                            <div class="col">
                                <a href="/profile/edit" type="button" class="btn-light btn btn-block"><i class="fas fa-edit"></i> Edit Profile</a>
                            </div>
                        </div>
                        {% if not is_granted('ROLE_OWNER')  or not is_granted("ROLE_CREATOR")  %}
                            <div class="row mb-3">
                                <div class="col">
                                    <a href="/profile/requestrole/creator" type="button" class="btn-outline-light btn  btn-block"><i class="fas fa-clipboard-question"></i> Request Creator Status</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                {% if "ROLE_CREATOR" in app.user.roles %}
                <div class="row">
                    <div class="col panel p-3">
                        <div class="row mb-3">
                            <div class="col">
                                <h3><i class="fas fa-book"></i> My Comics</h3>
                            </div>
                        </div>
                        {% if app.user.comics|length == 0 %}
                            <div class="row mb-3">
                                <div class="col">
                                    <h4>No comics listed</h4>
                                </div>
                            </div>
                        {% else %}
                            {% for comic in app.user.comics %}
                                {% include "profile/profile_comic_block.html.twig" with { comic: comic, settings:settings } %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </div>

        </div>
    </div>
    {% include "common/deletecomicmodal.html.twig" %}
{% endblock %}

{% block sidebar %}
    {% include "common/user-sidebar.html.twig" %}
{% endblock %}

templates/profile/profile_comic_block.html.twig
<div class="row profile-comic-row mb-4 ">
    <div class="col">
        <div class="row mb-1">
            <div class="col">
                <h4>{{ comic.name }}</h4>
            </div>
        </div>
        <div class="row mb-1">
            <div class="col offset-1"><a href="{{ settings.get.server_url }}/@{{ comic.slug }}">Latest Page</a></div>
        </div>
    </div>
    <div class="col-3">

        {% if comic.isactive == true and comic.isdeleted == false %}
        <div class="row">
            <div class="col">
                <div class="d-grid">
                    <a href="/page/{{ comic.slug }}/add" class="btn btn-light text-success"><i class="fas fa-file-circle-plus"></i> Add New Page</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% if comic.isactive == false and comic.isdeleted == false and ('ROLE_ADMIN' in app.user.getRoles() or settings.require_comic_approval == false)%}
            <div class="row">
                <div class="col">
                    <div class="d-grid">
                        <button class="btn btn-block btn-danger comic-delete" data-comic="{{ comic.slug }}" data-comicname="{{ comic.name }}"><i class="fas fa-trash"></i> Delete {{ comic.name }}</button>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="row mb-1">
            <div class="col btn-group">
                <a href="/page/{{ comic.slug }}" class="btn btn-success" title="Manage {{ comic.name }}"><i class="fas fa-toolbox"></i></a>
                <a href="/comic/{{ comic.slug }}/edit" type="button" class="btn btn-primary" title="Edit {{ comic.name }}"><i class="fas fa-edit"></i></a>
                <a href="/layout/{{ comic.slug }}" type="button" class="btn btn-info" title="Edit Layout for {{ comic.name }}"><i class="fas fa-gear"></i></a>
                {% if comic.isactive == true and comic.isdeleted == false %}
                    <a class="btn btn-warning" href="/comic/{{ comic.slug }}/deactivate" title="Deactivate {{ comic.name }}"><i class="fas fa-unlock"></i></a>
                {% else %}
                    {% if comic.isactive == false and comic.isdeleted == false and ('ROLE_ADMIN' in app.user.getRoles() or settings.require_comic_approval == false)%}
                        <a class="btn btn-light text-dark" href="/comic/{{ comic.slug }}/activate" title="Activate {{ comic.name }}"><i class="fas fa-lock-open"></i></a>
                    {% else %}
                        <button class="btn btn-block btn-dark" disabled title="Inactive"><i class="fas fa-lock"></i> Inactive</button>
                    {% endif %}
                {% endif %}
            </div>
        </div>


    </div>

</div>